### ISSUE TITLE
重新签名在iOS9上运行，启动就闪退

### ISSUE THREAD

**Issue by alexlee928** [rpplusplus/PokemonHook#1]
rt，请问作者是否可以指导一下？

**Comment by monycn** [comment]
你的证书中有你自己的设备吗？

**Comment by alexlee928** [comment]
必须有啊 都装上了

**Comment by sxiaojian88** [comment]
闪退应该是签名不正确

**Comment by red3** [comment]
我重签名后成功跑在了自己的设备上了。所以作者的包应该是没有问题的。

**Comment by alexlee928** [comment]
谢了二位 我再试试

**Comment by KittenYang** [comment]
你看看 console,我闪退是因为 libLocationFaker.dylib 的签名证书还是作者原来的证书，用重签 ipa 的证书签一遍  libLocationFaker.dylib 就行了。
