### ISSUE TITLE
重啓後定位會回到初始點

### ISSUE THREAD

**Issue by hirakujira** [rpplusplus/PokemonHook#11]
看起來是在 +(void)load 的時候沒有正確載入儲存的 fake_x 跟 fake_y 

我測試是在 - (CLLocationCoordinate2D) coordinate_ 再次檢查是否有儲存的 fake_x 跟 fake_y ，就能解決。

**Comment by alfredcc** [comment]
@hirakujira 如果需要更改代码必须要装 iOSOpenDev 的环境？

**Comment by rpplusplus** [comment]
我更新代码的时候并没有更新对应的 dylib，请自行编译。

**Comment by rpplusplus** [comment]
@alfredcc 是这样
