### ISSUE TITLE
iphone 5 "This application does not support this device's CPU type."

### ISSUE THREAD

**Issue by ji3g4m6zo6** [rpplusplus/PokemonHook#12]
谢谢虾神提供这么好的跨区源码

我在iphone 6s上顺利执行

想在自己的旧机器 iphone 5也安装下，没想到报错

"This application does not support this device's CPU type."

原版的Pokemon Go支持iPhone 5 的CPU，是不是我哪里设定错了？

在此请教大家，谢谢

**Comment by monycn** [comment]
你需要找个32位的越狱的手机去砸壳，比如iPhone5或5C，参考README里的最下面那个

**Comment by rpplusplus** [comment]
readme 最下面有写，我刚又添加了一个平时不容易注意到的坑，祝你旗开得胜。

**Comment by ghost** [comment]
大概中午12点的时候，兔兔助手的修复了这问题
