### ISSUE TITLE
Why only 32bit CPU？

### ISSUE THREAD

**Issue by red3** [rpplusplus/PokemonHook#13]
32bit CPU 是为了兼容性的考虑吗？还是说有其他限制？
从性能上考量，假如我要跑在 64bit 的机器上，是不是从 64bit 的越狱机器上 Clutch 更合适？
BTW，我尝试在自己的 iPad Air 上砸壳后成功安装在 6s 上.

**Comment by rpplusplus** [comment]
我提供的压缩包是拿 iPad mini4 砸出来的，只有 arm64 的指令集。所以下面写了一下，需要用 32bit 的童鞋该怎么做
