### ISSUE TITLE
请问虾大  pokemongo-resigned.ipa does not contain a valid Info.plist ？

### ISSUE THREAD

**Issue by Hearnseu** [rpplusplus/PokemonHook#14]
用xcode 安装时出现错误： pokemongo-resigned.ipa does not contain a valid Info.plist   (“CFBundleExecutable” specifies a file that is not executable)，请问该如何处理？谢谢

**Comment by wonderffee** [comment]
Info.plist里面的identifier应该与你签名的identifier一致的

**Comment by rpplusplus** [comment]
@Hearnseu 应该是你砸壳的时候 忘了 chmod 吧...
