### ISSUE TITLE
虾神,新版本29.0.2打包后注入的动态库好像没法生效

### ISSUE THREAD

**Issue by wenhhh** [rpplusplus/PokemonHook#16]

**Comment by rpplusplus** [comment]
居然又更新了......

**Comment by wenhhh** [comment]
求指教为何注入没有生效

**Comment by rpplusplus** [comment]
（我懒得折腾了怎么办

**Comment by rpplusplus** [comment]
亲测没问题...

**Comment by hello--world** [comment]
😄大神就是大神。我注入也失败，用虾神的就行。还得继续折腾。。。

**Comment by rpplusplus** [comment]
注意 chmod.... 严格按照我 readme 写应该没问题

**Comment by wenhhh** [comment]
已经弄好了 主要是没太明白yolo在做什么 现在已经明白了

**Comment by rpplusplus** [comment]
@WinHand 嗯，这个 repo 让我明白了大伙儿对 ipa 包里的东西以及 mach-o 并不了解，我公众号下一篇文章考虑写这个

**Comment by hello--world** [comment]
@WinHand @rpplusplus  哈哈，看了二位的对话，我也弄好了，我出现的问题是，yolo的没有在当前目录，继续折腾中。

**Comment by rpplusplus** [comment]
@hello--world 
![image](https://cloud.githubusercontent.com/assets/1753142/16869115/cadc5eba-4aad-11e6-8018-1f66576ae83c.png)
你可以配合 mach-o viewer 来看，就会发现 如果你带了个奇怪的路径 那肯定跪了

**Comment by hello--world** [comment]
@rpplusplus 嗯，谢谢，这软件好。我是看crash日志发现不能加载这dylib，显示的路径不对，最后弄好了。一般玩，一边学，折腾起来才有劲。
