### ISSUE TITLE
请问虾神

### ISSUE THREAD

**Issue by wu736139669** [rpplusplus/PokemonHook#19]
我自己制作了一个dylib的包，怎么弄进去打包呢。
执行 yolo pokemango libXXXX.dylib 如果叫做 LocationFaker.dylib 可以跳过这个看不懂。

**Comment by rpplusplus** [comment]
执行 yolo 实际上是在 pokemango 的 mach-o 里面加了一个关联，去找一个叫做 locationfaker.dylib 的库。所以如果你是同名的话，就不用执行 yolo 了

**Comment by soffchen** [comment]
所以应该是

如果叫做 libLocationFaker.dylib 可以跳过 

吧？应该包里自带的是 libLocationFaker.dylib

**Comment by rpplusplus** [comment]
otool -L pokemango 你就懂了
