### ISSUE TITLE
能不能那个半成品修改一下，经纬度加个零点几的随机数

### ISSUE THREAD

**Issue by monycn** [rpplusplus/PokemonHook#2]
设备上次因为白苹果，不得不升到正式版。没法去编译破解包了。求大神在那个定位到联合广场的基础上加一个零点几的随机经纬度，这样不至于每次打开应用都重生到一个点。只要能有个未签名的包就行。

**Comment by rpplusplus** [comment]
和正式版有什么关系？ 我用的 iOS 10 都没问题。 我现在更新了 代码，缓存 offset，就等于出生点固定，可以随便探索了
