### ISSUE TITLE
推荐使用 iOS App Signer

### ISSUE THREAD

**Issue by soffchen** [rpplusplus/PokemonHook#20]
https://github.com/DanTheMan827/ios-app-signer
- 可以自动寻找 ipa 包里面的 dylib 并自动重签名，无需对 libLocationFaker.dylib 再做处理
- 选择好 Profile 之后会自动修改 Info.plist 的 Bundle ID
- 可以修改 App Name

**Comment by rpplusplus** [comment]
乔学士修改的 iresign 也可以...这样的后果就是你永远都不知道 dylib 还需要签名了...
