### ISSUE TITLE
集成 Pusher

### ISSUE THREAD

**Issue by soffchen** [rpplusplus/PokemonHook#21]
请问有没有思考过集成 Pusher，然后通过 Pusher 来控制现在的坐标。
在下尝试了一下，没有成功 :(

**Comment by rpplusplus** [comment]
@soffchen 这个 Repo 只是告诉大家可以这么玩，大家想怎么玩就去研究吧。我个人只改一下坐标什么都不碰，游戏里开飞机就没意思了。想做外挂的话有的是东西可以玩啊
