### ISSUE TITLE
GPS Signal not found

### ISSUE THREAD

**Issue by soffchen** [rpplusplus/PokemonHook#22]
原地不动的时候经常会提示这个，不知道是什么原因，想不明白 :(

**Comment by aaaddress1** [comment]
純粹就是機子上GPS訊號接收不良吧？

**Comment by rpplusplus** [comment]
室内 GPS 信号丢失不是挺正常的么....你不能指望 WI-FI 定位的，如果我想只拿到 GPS 定位的话 就判断一下海拔是不是0，基站 WI-FI 定位都不会给海拔值
