### ISSUE TITLE
Signer did not match any installed provisioning profile

### ISSUE THREAD

**Issue by MStarlogo** [rpplusplus/PokemonHook#25]
Jul 19 10:09:19 Timde-iPhone CLTM[21] <Error>: CLTM: _subscription 0x0, _subscribedChannels 0x0
Jul 19 10:09:22 Timde-iPhone installd[15102] <Error>: 0x1005b4000 -[MICodeSigningVerifier performValidationWithError:]: 188: Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.P8yXiI/extracted/pokemongo.app identifier = com.nianticlabs.pokemongo type = 4> : 0xe8008015 (Signer did not match any installed provisioning profile)
Jul 19 10:09:22 Timde-iPhone installd[15102] <Error>: 0x1005b4000 -[MIInstaller performInstallationWithError:]: Verification stage failed
Jul 19 10:09:22 Timde-iPhone streaming_zip_conduit[15005] <Error>: 0x100594000 __MobileInstallationInstallForLaunchServices_block_invoke240: Returned error Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.P8yXiI/extracted/pokemongo.app identifier = com.nianticlabs.pokemongo type = 4> : 0xe8008015 (Signer did not match any installed provisioning profile)" UserInfo=0x13ed25590 {LibMISErrorNumber=-402620395, LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=188, FunctionName=-[MICodeSigningVerifier performValidationWithError:], NSLocalizedDescription=Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.P8yXiI/extracted/pokemongo.app identifier = com.nianticlabs.pokemongo type = 4> : 0xe8008015 (Signer did not match any installed provisioning profile)}

一直没搞懂这个Signer did not match any installed provisioning profile 具体哪个地方有什么问题，有谁碰到过吗

**Comment by rpplusplus** [comment]
签名问题
