### ISSUE TITLE
请问能否给我发一个可以直接安装的ipa？

### ISSUE THREAD

**Issue by JayWii** [rpplusplus/PokemonHook#4]
您好，我非常喜欢口袋妖怪这个游戏，但是我不会iOS开发，也没有签名用的证书，我非常想安装您这个版本来体验一下pokemonGO这个游戏，不知道能否给我发一个可以直接安装的ipa？要是可以那真是感激不尽

**Comment by rpplusplus** [comment]
抱歉，这是我不能接受的。去下载果盘游戏吧
