### ISSUE TITLE
xcode提示this application does not support this device's cpu type

### ISSUE THREAD

**Issue by wayne1943x** [rpplusplus/PokemonHook#5]
Hi,

我按照你的步骤，先签了lib，然后压缩，然后用fastlane签ipa，用xcode安装时提示this application does not support this device's cpu type，请问怎么解决。我是iphone 5

**Comment by xilin** [comment]
iPhone 5是32位设备。项目里带的ipa是64位的包。

**Comment by wayne1943x** [comment]
0.0 那只能我自己build lib，然后itunes上下iphone5的ipa来改？

**Comment by wayne1943x** [comment]
除了那个hook lib，还有其他需要的吗，用自己下的ipa来改，把lib放进去，可以安装了，但一直闪退，不懂ios怎么看日志

**Comment by xilin** [comment]
自己下的ipa要先解密吧？具体过程其实我也不是很懂，你可以找找资料。印象中是需要越狱机器才能砸出来的。
看日志就是连上设备然后用xcode或者其他工具看console log。

**Comment by wayne1943x** [comment]
Jul 10 20:34:35 Aero-Kangs-iPhone SpringBoard[48] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Jul 10 20:34:35 Aero-Kangs-iPhone SpringBoard[48] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Jul 10 20:34:35 Aero-Kangs-iPhone securityd[93] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Jul 10 20:34:35 Aero-Kangs-iPhone securityd[93] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Jul 10 20:34:35 Aero-Kangs-iPhone amfid[170] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Jul 10 20:34:35 Aero-Kangs-iPhone kernel[0] <Notice>: AppleFairplayTextCrypterSession::fairplayOpen() failed, error -42022
Jul 10 20:34:35 Aero-Kangs-iPhone com.apple.xpc.launchd[1](UIKitApplication:com.nianticlabs.pokemongo[0x7a59][414]) <Notice>: Service exited due to signal: Killed: 9
Jul 10 20:34:35 Aero-Kangs-iPhone assertiond[65] <Warning>: Unable to obtain a task name port right for pid 414: (os/kern) failure (5)
Jul 10 20:34:35 Aero-Kangs-iPhone SpringBoard[48] <Warning>: Unable to register for exec notifications: No such process
Jul 10 20:34:35 Aero-Kangs-iPhone SpringBoard[48] <Warning>: Unable to obtain a task name port right for pid 414: (os/kern) failure (5)
Jul 10 20:34:35 Aero-Kangs-iPhone SpringBoard[48] <Warning>: Unable to obtain a task name port right for <FBApplicationProcess: 0x14fc3c90; com.nianticlabs.pokemongo; pid: 414>
Jul 10 20:34:35 Aero-Kangs-iPhone SpringBoard[48] <Warning>: Application 'UIKitApplication:com.nianticlabs.pokemongo[0x7a59]' exited abnormally via signal.
Jul 10 20:34:36 Aero-Kangs-iPhone SpringBoard[48] <Warning>: Application '(null)' exited for an unknown reason.
Jul 10 20:34:36 Aero-Kangs-iPhone SpringBoard[48] <Warning>: Reply Error: Connection interrupted

**Comment by wayne1943x** [comment]
搞出来，可是看不懂。。。可能就是没砸壳。。

**Comment by xilin** [comment]
你这看起来是entitlements不对。再去找些资料学习一遍吧。

**Comment by rpplusplus** [comment]
是这样的，我手里已经没有 32位的越狱设备了，只有一台 iPad mini iOS 9 ，因为 App Slicing 所以拿出来的只有 64 bit...

如果你想在 32bit 设备上运行，就要按照我 blog 上说的，从砸壳那一步开始做。
