### ISSUE TITLE
感谢~ & 小小的解释

### ISSUE THREAD

**Issue by ycy233** [rpplusplus/PokemonHook#7]
感谢作者大大~
周五下载了未签名的代码包，和小伙伴研究了一晚上，搞定了签名和安装。
今天上来看到作者贴心地又更新了签名步骤~
解释下，好多人都不会大概是大家都是奔着游戏来的，本身可能都没接触过ios开发。
最后还是非常感谢，让我们玩到了这个游戏，很激动很开心(づ￣ 3￣)づ

**Comment by rpplusplus** [comment]
我个人很佩服那些连代码都看不懂靠百度研究出来签名和安装的人，他们有什么需求我一般都会去满足。但我很鄙视说自己是 iOS 开发，看在同行的面子上让我手把手教他。而且不止一个，被骚扰的很厉害。所以才加了那一句吐槽，见谅见谅
