### ISSUE TITLE
一直闪退，发现是dylib没有加载到。求解决办法

### ISSUE THREAD

**Issue by aya-iko** [rpplusplus/PokemonHook#9]
Dyld Error Message:
Dyld Message: Library not loaded: @executable_path/libLocationFaker.dylib
  Referenced from: /var/mobile/Containers/Bundle/Application/44D60225-FBC0-4CCC-B878-3F483CCAB3DE/pokemongo.app/pokemongo

**Comment by aya-iko** [comment]
搞定了。。。。。

**Comment by aya-iko** [comment]
还是不行。已经注入好了还是这个错误。用MachOView看发现已经注入进去了。就是一直闪退报Library not loaded

**Comment by rpplusplus** [comment]
首先请确定 dylib 已签名

**Comment by aya-iko** [comment]
可以了。确实是证书问题。

**Comment by rpplusplus** [comment]
讲真，为什么不好好看看 Readme 呢....

**Comment by aya-iko** [comment]
是我证书出了问题，我一直以为打进去了。之后用codesign -dv libLocationFaker.dylib 才发现没成功

**Comment by fuer4869** [comment]
我用Xcode编译签名注入不进去，后来是用codesign 注入进去的。你是怎么解决的？

**Comment by fuer4869** [comment]
虾神，请原谅我们这些即使看了readme也看不懂的人吧。。。

**Comment by xyzzhangfan** [comment]
@fuer4869 我一开始也是Xcode编译也是闪退，后来发现是只改了target里的code sign 和provisioning profile忘了改project里面。
